name: smart_fishery
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  blur: ^3.1.0
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  responsive_grid_list: ^1.3.2
  intl: ^0.18.1
  common:
    path: common
  dependencies:
    path: dependencies
  fitur_lihat_detail_kolam:
    path: fitur/fitur_lihat_detail_kolam
  fitur_input_kualitas_air:
    path: fitur/fitur_input_kualitas_air
  fitur_input_panen:
    path: fitur/fitur_input_panen
  fitur_input_sampling:
    path: fitur/fitur_input_sampling
  fitur_input_penyakit:
    path: fitur/fitur_input_penyakit
  fitur_buat_tambak:
    path: fitur/fitur_buat_tambak
  fitur_buat_kolam:
    path: fitur/fitur_buat_kolam
  http: ^1.1.0
  url_launcher: ^6.1.12
  confirm_dialog: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/