name: smart_fishery
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  blur: ^3.1.0
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  responsive_grid_list: ^1.3.2
  common:
    path: common
  dependencies:
    path: dependencies
  fitur_lihat_detail:
    path: fitur/fitur_lihat_detail
  fitur_input_kualitas_air:
    path: fitur/fitur_input_kualitas_air
  fitur_input_panen:
    path: fitur/fitur_input_panen

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/


